def image

pipeline{
    agent any
    stages{
        stage('Build'){
            steps{
                script{
                    image= docker.build("fran/jk-pipeline-demos:0.0.1","--pull -f 02/solution/Dockerfile 02/solution")
                }
            }
        }
        stage('Smoke test'){
            steps{
                script{
                    container= image.run()
                    container.stop()
                }
            }    
        }
        stage('Push'){
            steps{
                script{
                    withDockerRegistry([credentialsId: 'docker-hub', url:""]){
                        image.push()
                    }
                }
            }
        }
    }
}