pipeline{
    agent any

    environment{
        REALEASE='0.0.1'
    }

    stages{
        stages('Build'){
            agent any
            environment{
                LOG_LEVEL='INFO'
            }
            steps{
                echo "Building release ${RELEASE} with log level ${LOG_LEVEL}"
            }
        }
        stages('Test'){
            steps{
                echo "Testing, I can see release ${RELEASE} but not log level ${LOG_LEVEL}"
            }
        }
    }
}