pipeline {
    agent any

    environment {
        VERSION= sh([ script:'cd ./01/solution && npm run env | grep "nmp_package_version"', returnStdout: true]).trim()
        VERSION_RC= "rc.2"
    }

    stages {
        stage('Audit tools') {
            steps {
                sh '''
                    git version
                    docker version
                    node --version
                    npm version
                '''
            }
        }
        stage('Build') {
            steps {
                dir('./01/solution'){
                    echo "Building version ${VERSION} with suffix: ${VERSION_RC}"
                    sh '''
                        npm install
                        npm run build
                    '''
                }
            }
        }
        stage('Unit Test') {
            
            steps {
                dir('./01/solution'){
                    sh 'npm test'
                }
            }
        }
    }

    
}